from __future__ import annotations

import json
from pathlib import Path
from typing import Any

CATEGORIES = (
    "AI_TECH",
    "CREATIVE_AI",
    "PSYCHOLOGY",
    "HEALTH_LOOKS",
    "FASHION",
    "MARKETS",
    "CRYPTO",
    "DATA_SCIENCE",
    "POLICY",
)

DEFAULT_SOURCE_PATH = Path("data/feed_sources.json")
SOURCE_CONFIG_PATH = Path("config/feed_sources.json")
DEFAULT_ITEM_PATH = Path("data/feed_items.jsonl")
DEFAULT_RUN_DIR = Path("data/feed_runs")
DEFAULT_DB_PATH = Path("data/feed_app.sqlite3")
DEFAULT_USER_ID = "local"

DEFAULT_SOURCE_DEFINITIONS: tuple[dict[str, Any], ...] = (
    {
        "id": "openai-news",
        "name": "OpenAI News",
        "category": "AI_TECH",
        "feed_url": "https://openai.com/news/rss.xml",
        "site_url": "https://openai.com/news/",
    },
    {
        "id": "anthropic-news",
        "name": "Anthropic News",
        "category": "AI_TECH",
        "feed_url": "https://www.anthropic.com/news/rss.xml",
        "site_url": "https://www.anthropic.com/news",
    },
    {
        "id": "google-deepmind-blog",
        "name": "Google DeepMind Blog",
        "category": "AI_TECH",
        "feed_url": "https://deepmind.google/discover/blog/rss.xml",
        "site_url": "https://deepmind.google/discover/blog/",
    },
    {
        "id": "hugging-face-blog",
        "name": "Hugging Face Blog",
        "category": "AI_TECH",
        "feed_url": "https://huggingface.co/blog/feed.xml",
        "site_url": "https://huggingface.co/blog",
    },
    {
        "id": "simon-willison",
        "name": "Simon Willison",
        "category": "AI_TECH",
        "feed_url": "https://simonwillison.net/atom/everything/",
        "site_url": "https://simonwillison.net/",
    },
    {
        "id": "latent-space",
        "name": "Latent Space",
        "category": "AI_TECH",
        "feed_url": "https://www.latent.space/feed",
        "site_url": "https://www.latent.space/",
    },
    {
        "id": "nvidia-developer-blog",
        "name": "NVIDIA Developer Blog",
        "category": "AI_TECH",
        "feed_url": "https://developer.nvidia.com/blog/feed/",
        "site_url": "https://developer.nvidia.com/blog/",
    },
    {
        "id": "arxiv-cs-ai",
        "name": "arXiv cs.AI",
        "category": "AI_TECH",
        "feed_url": "http://export.arxiv.org/rss/cs.AI",
        "site_url": "https://arxiv.org/list/cs.AI/recent",
    },
    {
        "id": "arxiv-cs-lg",
        "name": "arXiv cs.LG",
        "category": "AI_TECH",
        "feed_url": "http://export.arxiv.org/rss/cs.LG",
        "site_url": "https://arxiv.org/list/cs.LG/recent",
    },
    {
        "id": "arxiv-cs-cl",
        "name": "arXiv cs.CL",
        "category": "AI_TECH",
        "feed_url": "http://export.arxiv.org/rss/cs.CL",
        "site_url": "https://arxiv.org/list/cs.CL/recent",
    },
    {
        "id": "runcomfy-workflows",
        "name": "RunComfy Workflows",
        "category": "CREATIVE_AI",
        "site_url": "https://www.runcomfy.com/workflows",
        "enabled": False,
        "notes": "Feed URL not confirmed yet. Add one in source management when available.",
    },
    {
        "id": "runcomfy-tutorials",
        "name": "RunComfy Tutorials",
        "category": "CREATIVE_AI",
        "site_url": "https://www.runcomfy.com/tutorials",
        "enabled": False,
        "notes": "Feed URL not confirmed yet. Add one in source management when available.",
    },
    {
        "id": "comfyui-blog-docs",
        "name": "ComfyUI Blog / Docs",
        "category": "CREATIVE_AI",
        "site_url": "https://docs.comfy.org/",
        "enabled": False,
        "notes": "Docs source kept as configurable feed-like source for v1.",
    },
    {
        "id": "comfyui-github-releases",
        "name": "ComfyUI GitHub Releases",
        "category": "CREATIVE_AI",
        "feed_url": "https://github.com/comfyanonymous/ComfyUI/releases.atom",
        "site_url": "https://github.com/comfyanonymous/ComfyUI/releases",
    },
    {
        "id": "civitai",
        "name": "Civitai",
        "category": "CREATIVE_AI",
        "site_url": "https://civitai.com/articles",
        "enabled": False,
        "notes": "Needs confirmed feed endpoint or API adapter later.",
    },
    {
        "id": "reddit-comfyui",
        "name": "Reddit r/ComfyUI",
        "category": "CREATIVE_AI",
        "feed_url": "https://www.reddit.com/r/comfyui/.rss",
        "site_url": "https://www.reddit.com/r/comfyui/",
    },
    {
        "id": "80-level",
        "name": "80 Level",
        "category": "CREATIVE_AI",
        "feed_url": "https://80.lv/rss/all.xml",
        "site_url": "https://80.lv/",
    },
    {
        "id": "cg-channel",
        "name": "CG Channel",
        "category": "CREATIVE_AI",
        "feed_url": "https://www.cgchannel.com/feed/",
        "site_url": "https://www.cgchannel.com/",
    },
    {
        "id": "runway",
        "name": "Runway",
        "category": "CREATIVE_AI",
        "site_url": "https://runwayml.com/research/",
        "enabled": False,
        "notes": "Configure feed URL if/when official RSS is confirmed.",
    },
    {
        "id": "luma-ai",
        "name": "Luma",
        "category": "CREATIVE_AI",
        "site_url": "https://lumalabs.ai/",
        "enabled": False,
        "notes": "Configure feed URL if/when official RSS is confirmed.",
    },
    {
        "id": "krea",
        "name": "Krea",
        "category": "CREATIVE_AI",
        "site_url": "https://www.krea.ai/",
        "enabled": False,
        "notes": "Configure feed URL if/when official RSS is confirmed.",
    },
    {
        "id": "arxiv-cs-cv",
        "name": "arXiv cs.CV",
        "category": "CREATIVE_AI",
        "feed_url": "http://export.arxiv.org/rss/cs.CV",
        "site_url": "https://arxiv.org/list/cs.CV/recent",
    },
    {
        "id": "arxiv-cs-gr",
        "name": "arXiv cs.GR",
        "category": "CREATIVE_AI",
        "feed_url": "http://export.arxiv.org/rss/cs.GR",
        "site_url": "https://arxiv.org/list/cs.GR/recent",
    },
    {
        "id": "arxiv-eess-as",
        "name": "arXiv eess.AS",
        "category": "CREATIVE_AI",
        "feed_url": "http://export.arxiv.org/rss/eess.AS",
        "site_url": "https://arxiv.org/list/eess.AS/recent",
    },
    {
        "id": "arxiv-cs-sd",
        "name": "arXiv cs.SD",
        "category": "CREATIVE_AI",
        "feed_url": "http://export.arxiv.org/rss/cs.SD",
        "site_url": "https://arxiv.org/list/cs.SD/recent",
    },
    {
        "id": "nature-human-behaviour",
        "name": "Nature Human Behaviour",
        "category": "PSYCHOLOGY",
        "feed_url": "https://www.nature.com/nathumbehav.rss",
        "site_url": "https://www.nature.com/nathumbehav/",
    },
    {
        "id": "psyarxiv",
        "name": "PsyArXiv",
        "category": "PSYCHOLOGY",
        "site_url": "https://osf.io/preprints/psyarxiv",
        "enabled": False,
        "notes": "Saved-search/API adapter belongs after v1 RSS foundation.",
    },
    {
        "id": "neuroscience-news",
        "name": "Neuroscience News",
        "category": "PSYCHOLOGY",
        "feed_url": "https://neurosciencenews.com/feed/",
        "site_url": "https://neurosciencenews.com/",
    },
    {
        "id": "behavioral-scientist",
        "name": "Behavioral Scientist",
        "category": "PSYCHOLOGY",
        "feed_url": "https://behavioralscientist.org/feed/",
        "site_url": "https://behavioralscientist.org/",
    },
    {
        "id": "nautilus",
        "name": "Nautilus",
        "category": "PSYCHOLOGY",
        "feed_url": "https://nautil.us/feed/",
        "site_url": "https://nautil.us/",
    },
    {
        "id": "arxiv-cs-hc",
        "name": "arXiv cs.HC",
        "category": "PSYCHOLOGY",
        "feed_url": "http://export.arxiv.org/rss/cs.HC",
        "site_url": "https://arxiv.org/list/cs.HC/recent",
    },
    {
        "id": "examine",
        "name": "Examine.com",
        "category": "HEALTH_LOOKS",
        "feed_url": "https://examine.com/feed/",
        "site_url": "https://examine.com/",
    },
    {
        "id": "pubmed-saved-searches",
        "name": "PubMed saved searches",
        "category": "HEALTH_LOOKS",
        "site_url": "https://pubmed.ncbi.nlm.nih.gov/",
        "enabled": False,
        "notes": "Add saved-search RSS URLs from PubMed manually.",
    },
    {
        "id": "foundmyfitness",
        "name": "FoundMyFitness",
        "category": "HEALTH_LOOKS",
        "feed_url": "https://www.foundmyfitness.com/rss.xml",
        "site_url": "https://www.foundmyfitness.com/",
    },
    {
        "id": "dermnet-nz",
        "name": "DermNet NZ",
        "category": "HEALTH_LOOKS",
        "site_url": "https://dermnetnz.org/",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "american-academy-dermatology",
        "name": "American Academy of Dermatology",
        "category": "HEALTH_LOOKS",
        "site_url": "https://www.aad.org/",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "hypebeast",
        "name": "Hypebeast",
        "category": "FASHION",
        "feed_url": "https://hypebeast.com/feed",
        "site_url": "https://hypebeast.com/",
    },
    {
        "id": "highsnobiety",
        "name": "Highsnobiety",
        "category": "FASHION",
        "feed_url": "https://www.highsnobiety.com/feed/",
        "site_url": "https://www.highsnobiety.com/",
    },
    {
        "id": "vogue-business",
        "name": "Vogue Business",
        "category": "FASHION",
        "feed_url": "https://www.voguebusiness.com/feed/rss",
        "site_url": "https://www.voguebusiness.com/",
    },
    {
        "id": "ssense-editorial",
        "name": "SSENSE Editorial",
        "category": "FASHION",
        "site_url": "https://www.ssense.com/en-us/editorial",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "grailed-dry-clean-only",
        "name": "Grailed / Dry Clean Only",
        "category": "FASHION",
        "site_url": "https://www.grailed.com/drycleanonly",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "sec-rss-edgar",
        "name": "SEC RSS / EDGAR",
        "category": "MARKETS",
        "feed_url": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&CIK=&type=&company=&dateb=&owner=include&start=0&count=40&output=atom",
        "site_url": "https://www.sec.gov/edgar/search/",
    },
    {
        "id": "sec-structured-disclosure-feeds",
        "name": "SEC structured disclosure feeds",
        "category": "MARKETS",
        "site_url": "https://www.sec.gov/structureddata",
        "enabled": False,
        "notes": "Needs more specific feed selection.",
    },
    {
        "id": "stratechery",
        "name": "Stratechery",
        "category": "MARKETS",
        "feed_url": "https://stratechery.com/feed/",
        "site_url": "https://stratechery.com/",
    },
    {
        "id": "matt-levine-money-stuff",
        "name": "Matt Levine / Money Stuff",
        "category": "MARKETS",
        "site_url": "https://www.bloomberg.com/account/newsletters/money-stuff",
        "enabled": False,
        "notes": "Newsletter source; no official public RSS configured.",
    },
    {
        "id": "semianalysis",
        "name": "SemiAnalysis",
        "category": "MARKETS",
        "feed_url": "https://www.semianalysis.com/feed",
        "site_url": "https://www.semianalysis.com/",
    },
    {
        "id": "aswath-damodaran",
        "name": "Aswath Damodaran",
        "category": "MARKETS",
        "feed_url": "https://aswathdamodaran.blogspot.com/feeds/posts/default",
        "site_url": "https://aswathdamodaran.blogspot.com/",
    },
    {
        "id": "techcrunch-startups",
        "name": "TechCrunch Startups",
        "category": "MARKETS",
        "feed_url": "https://techcrunch.com/category/startups/feed/",
        "site_url": "https://techcrunch.com/category/startups/",
    },
    {
        "id": "crunchbase-news",
        "name": "Crunchbase News",
        "category": "MARKETS",
        "feed_url": "https://news.crunchbase.com/feed/",
        "site_url": "https://news.crunchbase.com/",
    },
    {
        "id": "pitchbook-news",
        "name": "PitchBook News",
        "category": "MARKETS",
        "site_url": "https://pitchbook.com/news",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "dealroom",
        "name": "Dealroom",
        "category": "MARKETS",
        "site_url": "https://dealroom.co/blog",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "ethereum-foundation-blog",
        "name": "Ethereum Foundation Blog",
        "category": "CRYPTO",
        "feed_url": "https://blog.ethereum.org/feed.xml",
        "site_url": "https://blog.ethereum.org/",
    },
    {
        "id": "coindesk",
        "name": "CoinDesk",
        "category": "CRYPTO",
        "feed_url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "site_url": "https://www.coindesk.com/",
    },
    {
        "id": "the-block",
        "name": "The Block",
        "category": "CRYPTO",
        "feed_url": "https://www.theblock.co/rss.xml",
        "site_url": "https://www.theblock.co/",
    },
    {
        "id": "messari",
        "name": "Messari",
        "category": "CRYPTO",
        "site_url": "https://messari.io/",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "bankless",
        "name": "Bankless",
        "category": "CRYPTO",
        "site_url": "https://www.bankless.com/",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "our-world-in-data",
        "name": "Our World in Data",
        "category": "DATA_SCIENCE",
        "feed_url": "https://ourworldindata.org/atom.xml",
        "site_url": "https://ourworldindata.org/",
    },
    {
        "id": "fred",
        "name": "FRED",
        "category": "DATA_SCIENCE",
        "feed_url": "https://fredblog.stlouisfed.org/feed/",
        "site_url": "https://fredblog.stlouisfed.org/",
    },
    {
        "id": "eurostat",
        "name": "Eurostat",
        "category": "DATA_SCIENCE",
        "site_url": "https://ec.europa.eu/eurostat/",
        "enabled": False,
        "notes": "Needs specific RSS endpoint selection.",
    },
    {
        "id": "datawrapper-blog",
        "name": "Datawrapper Blog",
        "category": "DATA_SCIENCE",
        "feed_url": "https://blog.datawrapper.de/feed/",
        "site_url": "https://blog.datawrapper.de/",
    },
    {
        "id": "observable-blog",
        "name": "Observable Blog",
        "category": "DATA_SCIENCE",
        "feed_url": "https://observablehq.com/blog/rss.xml",
        "site_url": "https://observablehq.com/blog",
    },
    {
        "id": "kaggle-blog",
        "name": "Kaggle Blog",
        "category": "DATA_SCIENCE",
        "feed_url": "https://medium.com/feed/kaggle-blog",
        "site_url": "https://medium.com/kaggle-blog",
    },
    {
        "id": "european-commission",
        "name": "European Commission",
        "category": "POLICY",
        "site_url": "https://ec.europa.eu/commission/presscorner/home/en",
        "enabled": False,
        "notes": "Needs specific RSS/API endpoint selection.",
    },
    {
        "id": "european-parliament",
        "name": "European Parliament",
        "category": "POLICY",
        "feed_url": "https://www.europarl.europa.eu/rss/doc/top-stories/en.xml",
        "site_url": "https://www.europarl.europa.eu/news/en",
    },
    {
        "id": "federal-register",
        "name": "Federal Register",
        "category": "POLICY",
        "feed_url": "https://www.federalregister.gov/documents/search.rss",
        "site_url": "https://www.federalregister.gov/",
    },
    {
        "id": "fda",
        "name": "FDA",
        "category": "POLICY",
        "site_url": "https://www.fda.gov/news-events/fda-newsroom",
        "enabled": False,
        "notes": "Pick specific FDA feed from its RSS feed list.",
    },
    {
        "id": "ftc",
        "name": "FTC",
        "category": "POLICY",
        "site_url": "https://www.ftc.gov/news-events/news/press-releases",
        "enabled": False,
        "notes": "Configure only if official feed URL is confirmed.",
    },
    {
        "id": "doj-antitrust",
        "name": "DOJ Antitrust",
        "category": "POLICY",
        "feed_url": "https://www.justice.gov/feeds/atr-news.xml",
        "site_url": "https://www.justice.gov/atr",
    },
    {
        "id": "sec-policy-feeds",
        "name": "SEC policy feeds",
        "category": "POLICY",
        "feed_url": "https://www.sec.gov/rss/news/press.xml",
        "site_url": "https://www.sec.gov/newsroom/press-releases",
    },
)


def load_source_definitions(path: Path = SOURCE_CONFIG_PATH) -> tuple[dict[str, Any], ...]:
    if not path.exists():
        return DEFAULT_SOURCE_DEFINITIONS
    data = json.loads(path.read_text(encoding="utf-8"))
    sources = data.get("sources") if isinstance(data, dict) else data
    if not isinstance(sources, list):
        raise ValueError(f"Source config must contain a sources list: {path}")
    return tuple(source for source in sources if isinstance(source, dict))
